---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-yaml

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v1.0.0
    hooks:
      - id: encryption-check

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.16.2
    hooks:
      - id: ansible-lint
        args: ["-c", ".ansible-lint"]
        files: \.(yaml|yml)$
        # entry: ansible-lint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        files: integrations/docs
        entry: markdownlint -c .markdownlint.yml

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.4.3-1
    hooks:
      - id: shfmt

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ['-d {extends: default, rules: {line-length: {max: 120}}}']
