---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-yaml
        exclude: tasks/zsh_playbook.yml  #TODO?

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v0.1.2
    hooks:
      - id: encryption-check

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.10.0
    hooks:
      - id: ansible-lint
        args: ["-c", ".ansible-lint"]
        files: \.(yaml|yml)$

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2
    hooks:
      - id: shfmt
        exclude: files/to-home-dir #TODO?

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d {extends: default, rules: {line-length: {max: 120}}}']
        exclude: (.yamllint|sweep.yaml)
