repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-builtin-literals
    - id: check-yaml

  - repo: https://github.com/jorisroovers/gitlint
    rev:  "v0.19.1"
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.32.0"
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible/ansible-lint
    rev: "v6.16.2"
    hooks:
      - id: ansible-lint

  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: "v1.0.0"
    hooks:
      - id: encryption-check
  #
  # autoflake
  # isort
  # black
  # flake8
